"""empty message

Revision ID: 4ae5736522da
Revises: 675c431fc32e
Create Date: 2021-03-07 16:27:01.529280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ae5736522da'
down_revision = '675c431fc32e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('name_user', sa.String(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'users', ['name_user'], ['nick_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'name_user')
    # ### end Alembic commands ###
